### ISSUE TITLE
Configure Twitter template params

### ISSUE THREAD

**Issue by robertwtucker** [robertwtucker/robertwtucker-site#10]
Need to set up Twitter params so that any tweets linking back to posts are properly formatted.

- [x] Add default image to `config.yaml`.

```
params:
  description: Robert Tucker's personal website
  images:
  - site-feature-image.jpg
```

- [x] Update front-matter for any post that has its own image.

```
description: Text about this post
images:
- post-cover.png
title: Post title
```
